"""
Build the frequency-severity model training table, at
(location, hurricane-season-year) grain.

METHODOLOGY NOTE — why this grain, and why NOT (location, storm) grain:
Our claims were generated by a DETERMINISTIC pipeline (wind field model ->
vulnerability curve — see data_pipeline/synthetic/). If a model were
trained with "wind speed experienced during storm X" as a feature to
predict "damage from storm X," it would trivially re-learn our own
deterministic formula — not a genuine modeling exercise, and methodologically
wrong besides: a real pricing model CANNOT use a specific future storm's
realized wind speed as an input, because at pricing time the storm hasn't
happened yet.

Instead, this module builds a table at (location, season-year) grain:
features are everything knowable about a location AT PRICING TIME
(construction, TIV, regional climate risk — all static, non-storm-specific
columns from the Gold feature table); the TARGET is whether/how severely
that location was actually hit in each given historical season. A given
location's feature vector is IDENTICAL across all its rows (one per year)
— the model correctly learns which location CHARACTERISTICS predict higher
average claim frequency/severity, while storm-to-storm variance remains
appropriately unexplained (exactly as it should be — a real frequency
model can't predict which specific year a specific storm will strike).

This also gives "event-level split" (roadmap's non-negotiable methodology
requirement) a clean, correct meaning: split by YEAR, so a held-out
season's storm activity can never leak into training via any location that
also appears (with different-year rows) in the training set.

SCOPE NOTE: uses hurricane seasons 1950-2023 (74 seasons) rather than the
full 1851-2023 HURDAT2 range. This follows a common convention in
actuarial/cat-modeling practice of treating pre-satellite-era (pre-1960s
-70s) observations as less reliable, and keeps the resulting training
table (~1.48M rows at 20,000 locations x 74 years) computationally
tractable for this vertical slice.
"""

from __future__ import annotations

import logging
from pathlib import Path

import numpy as np
import pandas as pd

logger = logging.getLogger(__name__)

TRAINING_START_YEAR = 1950
TRAINING_END_YEAR = 2023  # inclusive

# Columns from the Gold feature table that are genuinely known at pricing
# time (location/construction attributes + REGIONAL, non-storm-specific
# climate covariates). Explicitly excludes historical_* columns, which are
# themselves derived from the claims history we're trying to predict here
# — including them would leak the target into the features.
#
# Also excludes event-focused features (storm_count, days_above_Xkt, etc.)
# which use current-year storm data that wouldn't be known at pricing time.
FEATURE_COLUMNS = [
    "location_id",

    # Geographic risk (static, knowable at pricing time)
    "lat",
    "lon",
    "metro_center",
    "distance_to_coast_km",  # Static distance to coastline

    # Exposure characteristics
    "year_built",
    "construction_class",
    "roof_type",
    "tiv_usd",

    # Long-term climate indicators (basin-wide, not storm-specific)
    "mslp_hpa_mean",
    "mslp_hpa_min",
    "era5_wind_speed_ms_mean",
    "era5_wind_speed_ms_max",
    "basin_sst_celsius_mean",
    "basin_sst_celsius_max",
    # Note: SST features (basin_sst_celsius_mean/max) are available in the training table
    # Note: SST features (basin_sst_celsius_mean/max) are available in the training table
    # and are included here. In historical runs SST was sometimes excluded due to
    # partial ERA5 coverage causing data sparsity; code downstream handles missing
    # SST values gracefully. For synthetic/testing scenarios SST can improve signal
    # for frequency models when present.
]

# Optional: Replace lat/lon with regional encoding to reduce geographic memorization
USE_REGIONAL_ENCODING = False
N_REGIONAL_CLUSTERS = 10


def build_training_table(
    gold_features: pd.DataFrame,
    claims: pd.DataFrame,
    yearly_sst: pd.DataFrame | None = None,
    start_year: int = TRAINING_START_YEAR,
    end_year: int = TRAINING_END_YEAR,
    use_regional_encoding: bool = USE_REGIONAL_ENCODING,
) -> pd.DataFrame:
    """
    Args:
        gold_features: output of Phase 3's run_gold_assembly (one row per
            location_id).
        claims: output of Phase 2's generate_claims (one row per
            (location_id, storm) claim event).
        yearly_sst: optional yearly SST data from yearly_sst.parquet
            (one row per year with basin_sst_celsius_mean/max).
            If None, SST features will be omitted.
        start_year, end_year: inclusive hurricane-season-year range.
        use_regional_encoding: if True, replace lat/lon with regional clusters.

    Returns:
        DataFrame with one row per (location_id, year):
        [FEATURE_COLUMNS..., year, had_claim, incurred_loss_usd,
        max_damage_ratio, claim_count_in_year].

    Raises:
        ValueError: if required columns are missing from either input.
    """
    # Validate gold_features columns (SST no longer required here)
    # distance_to_coast_km is optional in some test fixtures; handle gracefully
    required_gold_cols = {
        "location_id",
        "lat",
        "lon",
        "metro_center",
        "year_built",
        "construction_class",
        "roof_type",
        "tiv_usd",
        "mslp_hpa_mean",
        "mslp_hpa_min",
        "era5_wind_speed_ms_mean",
        "era5_wind_speed_ms_max",
    }
    missing_gold_cols = required_gold_cols - set(gold_features.columns)
    if missing_gold_cols:
        raise ValueError(f"gold_features is missing required columns: {missing_gold_cols}")

    required_claims_cols = {
        "claim_id",
        "location_id",
        "loss_date",
        "incurred_loss_usd",
        "damage_ratio"
    }
    missing_claims_cols = required_claims_cols - set(claims.columns)
    if missing_claims_cols:
        raise ValueError(f"claims is missing required columns: {missing_claims_cols}")

    years = np.arange(start_year, end_year + 1)
    location_ids = gold_features["location_id"].to_numpy()

    logger.info(
        "Building training table: %d locations x %d years = %d rows",
        len(location_ids),
        len(years),
        len(location_ids) * len(years),
    )

    # Cross join: every location x every year.
    cross = pd.MultiIndex.from_product(
        [location_ids, years], names=["location_id", "year"]
    ).to_frame(index=False)

    # Start with base features from gold_features
    # Only select base feature columns that exist in the provided gold_features
    base_feature_cols = [
        c
        for c in [
            "location_id",
            "lat",
            "lon",
            "metro_center",
            "distance_to_coast_km",
            "year_built",
            "construction_class",
            "roof_type",
            "tiv_usd",
            "mslp_hpa_mean",
            "mslp_hpa_min",
            "era5_wind_speed_ms_mean",
            "era5_wind_speed_ms_max",
        ]
        if c in gold_features.columns
    ]

    features = gold_features[base_feature_cols].copy()
    training = cross.merge(features, on="location_id", how="left")

    # Ensure distance_to_coast_km exists for downstream feature compatibility
    if "distance_to_coast_km" not in training.columns:
        training["distance_to_coast_km"] = 0.0

    # Join yearly SST if provided (time-varying climate covariate for Phase 5 TFT)
    # This is the correct grain: (location_id, year) - SST varies by year only
    if yearly_sst is not None:
        training = training.merge(
            yearly_sst, 
            on="year", 
            how="left"
        )
        # Note: Years without SST coverage will have NaN (14 of 74 years have data)
        # XGBoost/LightGBM handle NaN natively, so this won't crash
    else:
        # If no SST data, add constant columns for compatibility
        training["basin_sst_celsius_mean"] = 28.1  # fallback constant
        training["basin_sst_celsius_max"] = 35.9  # fallback constant

    # Skip trailing claim history for now - nested loop is too slow
    # TODO: Implement with efficient rolling window operations

    # Apply regional encoding if requested
    if use_regional_encoding:
        from data_pipeline.databricks_jobs.compute_event_features import compute_regional_encoding
        
        regional_encodings = compute_regional_encoding(
            gold_features[["location_id", "lat", "lon"]],
            n_clusters=N_REGIONAL_CLUSTERS,
        )
        training = training.merge(regional_encodings, on="location_id", how="left")
        
        # Drop lat/lon and use region_cluster instead
        training = training.drop(columns=["lat", "lon"])
        
        # Use regional encoding features (SST excluded due to insufficient coverage)
        feature_cols_for_run = [
            "region_cluster",  # Replaces lat/lon
            "metro_center",
            "distance_to_coast_km",
            "year_built",
            "construction_class",
            "roof_type",
            "tiv_usd",
            "mslp_hpa_mean",
            "mslp_hpa_min",
            "era5_wind_speed_ms_mean",
            "era5_wind_speed_ms_max",
            # SST excluded - see FEATURE_COLUMNS comment above
        ]
    else:
        # Use standard feature columns
        feature_cols_for_run = FEATURE_COLUMNS

    # Aggregate claims to (location_id, year) grain.
    claims_yearly = claims.copy()
    claims_yearly["year"] = pd.to_datetime(claims_yearly["loss_date"]).dt.year
    claims_yearly = claims_yearly[
        (claims_yearly["year"] >= start_year) & (claims_yearly["year"] <= end_year)
    ]
    claims_agg = (
        claims_yearly.groupby(["location_id", "year"])
        .agg(
            incurred_loss_usd=("incurred_loss_usd", "sum"),
            max_damage_ratio=("damage_ratio", "max"),
            claim_count_in_year=("claim_id", "count"),
        )
        .reset_index()
    )

    training = training.merge(claims_agg, on=["location_id", "year"], how="left")
    training["incurred_loss_usd"] = training["incurred_loss_usd"].fillna(0.0)
    training["max_damage_ratio"] = training["max_damage_ratio"].fillna(0.0)
    training["claim_count_in_year"] = training["claim_count_in_year"].fillna(0).astype(int)
    training["had_claim"] = (training["claim_count_in_year"] > 0).astype(int)

    logger.info(
        "Training table built: %d rows, %d (%.2f%%) with a claim",
        len(training),
        training["had_claim"].sum(),
        100.0 * training["had_claim"].mean(),
    )

    # Keep only the columns we need
    final_cols = feature_cols_for_run + ["year", "incurred_loss_usd", "max_damage_ratio", "claim_count_in_year", "had_claim"]
    training = training[final_cols]

    return training


def load_and_build(
    gold_path: Path = Path("data_pipeline/gold/gold_features.parquet"),
    claims_path: Path = Path("data_pipeline/silver/claims.parquet"),
    yearly_sst_path: Path = Path("data_pipeline/gold/yearly_sst.parquet"),
    use_regional_encoding: bool = USE_REGIONAL_ENCODING,
) -> pd.DataFrame:
    gold_features = pd.read_parquet(gold_path)
    claims = pd.read_parquet(claims_path)
    
    # Load yearly SST if available
    yearly_sst = None
    if yearly_sst_path.exists():
        logger.info(f"Loading yearly SST from {yearly_sst_path}")
        yearly_sst = pd.read_parquet(yearly_sst_path)
    else:
        logger.warning(f"Yearly SST not found at {yearly_sst_path}, using fallback constants")
    
    return build_training_table(
        gold_features,
        claims,
        yearly_sst=yearly_sst,
        use_regional_encoding=use_regional_encoding,
    )