"""
Severity model: LightGBM regressor predicting expected damage ratio GIVEN
a claim occurred (the "severity" half of the classical two-part
frequency-severity model — see train_frequency.py for the "frequency"
half).

MONOTONIC CONSTRAINT NOTE — adapted from the roadmap's original spec:
The roadmap's original plan called for a monotonic constraint on
"wind-speed feature" (loss must not decrease as wind speed increases).
That specific feature does not exist in this model's feature set BY
DESIGN — see build_training_table.py's methodology note: a per-storm wind
feature would leak the deterministic damage-simulation formula, since our
claims were generated by a known function of wind speed. The nearest
methodologically-sound analog available at pricing time is
basin_sst_celsius_mean: physically, a warmer Gulf provides more energy for
hurricane intensification, so expected severity should not DECREASE as
basin SST increases. This constraint is applied here instead, serving the
same regulatory-interpretability purpose (a monotonic, physically-grounded
constraint a regulator can sanity-check) as the original spec intended.
"""

from __future__ import annotations

import logging

import lightgbm as lgb
import pandas as pd
from sklearn.metrics import mean_absolute_error, r2_score

from ml.frequency_severity.train_frequency import prepare_features

logger = logging.getLogger(__name__)

MONOTONIC_INCREASING_FEATURE = "basin_sst_celsius_mean"


def build_monotone_constraints(columns: pd.Index) -> list[int]:
    """
    LightGBM's monotone_constraints expects one entry per feature column,
    in column order: 1 = must be non-decreasing, -1 = non-increasing,
    0 = unconstrained. Only MONOTONIC_INCREASING_FEATURE is constrained;
    everything else (including all one-hot-encoded categorical columns) is
    left free.
    """
    return [1 if col == MONOTONIC_INCREASING_FEATURE else 0 for col in columns]


def train_severity_model(
    train_df: pd.DataFrame,
    test_df: pd.DataFrame,
    target_col: str = "max_damage_ratio",
    seed: int = 42,
) -> tuple[lgb.LGBMRegressor, dict]:
    """
    Trains ONLY on rows where had_claim == 1 (the two-part model's
    "severity given a claim" component — training on all rows, including
    the ~non-claim majority, would bias the severity estimate toward zero).

    Raises:
        ValueError: if either train_df or test_df has zero positive
            (had_claim==1) rows — this would silently produce a
            meaningless model otherwise.
    """
    train_claims = train_df[train_df["had_claim"] == 1]
    test_claims = test_df[test_df["had_claim"] == 1]

    if len(train_claims) == 0:
        raise ValueError("No positive (had_claim=1) rows in train_df — cannot train severity model")
    if len(test_claims) == 0:
        raise ValueError("No positive (had_claim=1) rows in test_df — cannot evaluate severity model")

    X_train = prepare_features(train_claims)
    X_test = prepare_features(test_claims).reindex(columns=X_train.columns, fill_value=0)
    y_train = train_claims[target_col]
    y_test = test_claims[target_col]

    constraints = build_monotone_constraints(X_train.columns)

    model = lgb.LGBMRegressor(
        n_estimators=200,
        max_depth=4,
        learning_rate=0.05,
        subsample=0.8,
        colsample_bytree=0.8,
        monotone_constraints=constraints,
        random_state=seed,
        verbosity=-1,
    )
    model.fit(X_train, y_train)

    train_pred = model.predict(X_train)
    test_pred = model.predict(X_test)

    metrics = {
        "train_mae": mean_absolute_error(y_train, train_pred),
        "test_mae": mean_absolute_error(y_test, test_pred),
        "train_r2": r2_score(y_train, train_pred),
        "test_r2": r2_score(y_test, test_pred),
        "n_train": len(train_claims),
        "n_test": len(test_claims),
    }

    logger.info("Severity model metrics: %s", metrics)
    return model, metrics