"""
Regulatory Agent for RAG-grounded Solvency II & Treaty Wording Q&A.

Uses the Regulatory RAG Index (`rag_index/chunk_and_embed.py`) to query EIOPA Solvency II
Delegated Regulation (EU) 2015/35 and standard treaty clause libraries.
Enforces strict low-confidence refusal to prevent regulatory hallucinations.

Usage:
    python -m agents.regulatory_agent.regulatory_agent [--query "What is Article 105 SCR VaR?"]
"""

from __future__ import annotations

import argparse
import logging
from typing import Any

from rag_index.chunk_and_embed import get_rag_index

logger = logging.getLogger(__name__)


class RegulatoryAgent:
    """
    Agent responsible for RAG-grounded regulatory Q&A and treaty clause interpretation.
    """

    def __init__(self, min_confidence_score: float = 0.20):
        self.rag_index = get_rag_index()
        self.min_confidence_score = min_confidence_score
        logger.info("Initialized RegulatoryAgent with RAG Index.")

    def handle_query(self, query: str, context: dict[str, Any] | None = None) -> dict[str, Any]:
        """
        Query the RAG index and draft a grounded response with citations.

        Args:
            query: User regulatory query text.
            context: Optional contextual parameters.

        Returns:
            Dictionary containing response, citations list, and refusal flag.
        """
        logger.info("RegulatoryAgent searching RAG index for query: '%s'", query)

        results = self.rag_index.search(query, top_k=3, min_score_threshold=self.min_confidence_score)

        if not results:
            refusal_msg = (
                f"I cannot answer this question with sufficient regulatory confidence based on the indexed "
                f"Solvency II regulations and treaty clause library (no matching passage above confidence threshold {self.min_confidence_score:.2f}). "
                f"Please consult official EIOPA / NAIC regulatory publications."
            )
            return {
                "intent": "regulatory",
                "response": refusal_msg,
                "citations": [],
                "refused_to_answer": True,
            }

        # Build citations and grounded response
        citations = []
        citations_text_block = ""

        for idx, res in enumerate(results, 1):
            cite_entry = {
                "doc_name": res["doc_name"],
                "article_id": res["article_id"],
                "section": res["section"],
                "score": res["score"],
            }
            citations.append(cite_entry)

            citations_text_block += f"### [{idx}] {res['article_id']} ({res['doc_name']} — Relevance Score: {res['score']:.2f})\n"
            citations_text_block += f"> {res['text']}\n\n"

        main_answer = (
            f"# Solvency II & Treaty Regulatory Guidance\n\n"
            f"Based on the indexed regulation text, here are the applicable articles and clauses:\n\n"
            f"{citations_text_block}"
            f"---\n"
            f"*This regulatory response was generated by ClimateGuard AI Regulatory Agent with 100% citation grounding.*"
        )

        return {
            "intent": "regulatory",
            "response": main_answer,
            "citations": citations,
            "refused_to_answer": False,
        }


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(name)s: %(message)s")

    parser = argparse.ArgumentParser(description="Regulatory Agent")
    parser.add_argument("--query", type=str, default="What are the 72-hour hours clause provisions under Article 118?", help="Regulatory question")
    args = parser.parse_args()

    agent = RegulatoryAgent()
    res = agent.handle_query(args.query)

    print("\n" + "=" * 70)
    print("REGULATORY AGENT OUTPUT")
    print("=" * 70)
    print(res["response"])
    print("=" * 70)
